apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: new-devops-next-js-better-auth-secret
  namespace: teem
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: teams-dev/teem/BETTER_AUTH_SECRET
